# Generated by Django 5.0 on 2025-11-13 12:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.TextField(help_text='URL or text data to encode in QR code')),
                ('device_id', models.CharField(db_index=True, help_text='Browser/device fingerprint for tracking history', max_length=255)),
                ('qr_image', models.ImageField(blank=True, help_text='Generated QR code image', null=True, upload_to='qr_codes/')),
                ('scan_count', models.IntegerField(default=0, help_text='Number of times QR was accessed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_id', '-created_at'], name='qr_api_qrco_device__11d34f_idx')],
            },
        ),
    ]
